# Generated by Django 5.2.15 on 2026-09-20 01:14

import django.db.models.deletion
import torneos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_jugador_celular_organizador_celular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: 7ma, 6ta, 5ta', max_length=50)),
                ('cupo_minimo', models.PositiveIntegerField(default=3, help_text='Mínimo de parejas inscriptas para habilitar la categoría.')),
                ('cupo_maximo', models.PositiveIntegerField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(default=torneos.models.default_codigo, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('sede', models.CharField(blank=True, help_text='Club/cancha y ciudad.', max_length=150)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_limite_inscripcion', models.DateField()),
                ('precio_inscripcion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('formato', models.CharField(choices=[('grupos_eliminacion', 'Fase de grupos (zonas) + eliminación directa'), ('solo_eliminacion', 'Solo eliminación directa')], default='grupos_eliminacion', max_length=30)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador (no visible para jugadores)'), ('publicado', 'Publicado (abierto a inscripción)'), ('cerrado', 'Cerrado')], default='borrador', max_length=15)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneos', to='accounts.organizador')),
            ],
            options={
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_real', models.CharField(blank=True, help_text='Categoría real del jugador si es distinta a la declarada.', max_length=50)),
                ('nombre_1', models.CharField(max_length=150, verbose_name='Apellido y nombre')),
                ('dni_1', models.CharField(max_length=20, verbose_name='DNI')),
                ('localidad_1', models.CharField(max_length=100, verbose_name='Localidad')),
                ('socio_1', models.BooleanField(default=False, verbose_name='Es socio del club')),
                ('club_socio_1', models.CharField(blank=True, help_text='Puede ser un club distinto al organizador.', max_length=150, verbose_name='Club del que es socio')),
                ('carnet_socio_1', models.CharField(blank=True, max_length=50, verbose_name='N° de carnet')),
                ('nombre_2', models.CharField(max_length=150, verbose_name='Apellido y nombre')),
                ('dni_2', models.CharField(max_length=20, verbose_name='DNI')),
                ('localidad_2', models.CharField(max_length=100, verbose_name='Localidad')),
                ('socio_2', models.BooleanField(default=False, verbose_name='Es socio del club')),
                ('club_socio_2', models.CharField(blank=True, help_text='Puede ser un club distinto al organizador.', max_length=150, verbose_name='Club del que es socio')),
                ('carnet_socio_2', models.CharField(blank=True, max_length=50, verbose_name='N° de carnet')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono de la pareja')),
                ('disponibilidad', models.CharField(blank=True, help_text='No excluyente: solo mejora el emparejamiento cuando es posible.', max_length=255, verbose_name='Días/horarios disponibles')),
                ('metodo_pago', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('transferencia', 'Transferencia'), ('efectivo', 'Efectivo (en la cancha)')], default='transferencia', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago/habilitación'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='torneos.categoria')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='torneos.torneo')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='torneos.torneo'),
        ),
    ]
