# Generated by Django 5.2.15 on 2026-09-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0002_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('1ra LIBRE', '1ra LIBRE'), ('2da LIBRE', '2da LIBRE'), ('3ra LIBRE', '3ra LIBRE'), ('4ta LIBRE', '4ta LIBRE'), ('5ta LIBRE', '5ta LIBRE'), ('6ta LIBRE', '6ta LIBRE'), ('7ma LIBRE', '7ma LIBRE'), ('8va LIBRE', '8va LIBRE'), ('1ra DAMAS', '1ra DAMAS'), ('2da DAMAS', '2da DAMAS'), ('3ra DAMAS', '3ra DAMAS'), ('4ta DAMAS', '4ta DAMAS'), ('5ta DAMAS', '5ta DAMAS'), ('6ta DAMAS', '6ta DAMAS'), ('7ma DAMAS', '7ma DAMAS'), ('8va DAMAS', '8va DAMAS'), ('1ra MIXTO', '1ra MIXTO'), ('2da MIXTO', '2da MIXTO'), ('3ra MIXTO', '3ra MIXTO'), ('4ta MIXTO', '4ta MIXTO')], help_text="Categoría estándar (evita variantes como '5ta LIBRE' vs '5ta libre').", max_length=50),
        ),
    ]
