# Generated by Django 5.2.15 on 2026-09-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0004_torneo_latitud_torneo_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
