# Generated by Django 5.2.15 on 2026-09-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0005_alter_torneo_latitud_alter_torneo_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='celular_1',
            field=models.CharField(blank=True, max_length=30, verbose_name='Celular'),
        ),
    ]
