# Generated by Django 5.2.15 on 2026-09-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0006_inscripcion_celular_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='sumatoria_minima',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Solo para modalidad 'Por sumatoria': suma mínima de las categorías oficiales de la pareja (1ra=1 .. 8va=8) para poder inscribirse acá.", null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='categoria_oficial_1',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1ra es la más alta. Queda guardada en el perfil del jugador.', null=True, verbose_name='Categoría oficial'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='categoria_oficial_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Categoría oficial del compañero'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='categorias_permitir_subir',
            field=models.PositiveSmallIntegerField(default=0, help_text="Solo para modalidad 'Por categoría': cuántas categorías por encima de la que le corresponde a la pareja se le permite jugar (0 = solo la suya)."),
        ),
        migrations.AddField(
            model_name='torneo',
            name='modalidad_categoria',
            field=models.CharField(choices=[('por_categoria', 'Por categoría (según el jugador de mayor nivel)'), ('por_sumatoria', 'Por sumatoria (suma de las categorías de la pareja)')], default='por_categoria', help_text='Cómo se valida la categoría de la pareja al inscribirse.', max_length=20),
        ),
    ]
