# Generated by Django 5.2.15 on 2026-09-30 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0007_categoria_sumatoria_minima_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Quién hizo la inscripción (Jugador 1). Nulo en inscripciones muy viejas, de antes de exigir login para inscribirse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
