# Generated by Django 5.2.15 on 2026-10-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0008_inscripcion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='sumatoria_valor',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Solo para modalidad 'Por sumatoria': el torneo es exclusivamente 'SUMA <valor>' — la suma de categorías de la pareja tiene que ser ≥ este valor. Reemplaza a la lista de categorías.", null=True),
        ),
    ]
