# Generated by Django 5.2.15 on 2026-10-05 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0009_torneo_sumatoria_valor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='etapa',
            field=models.CharField(choices=[('inscripcion', 'Inscripción'), ('organizacion_grupos', 'Organizando fase de grupos'), ('juego_grupos', 'Jugando fase de grupos'), ('grupos_finalizados', 'Fase de grupos finalizada (falta llave)'), ('juego_llave', 'Jugando llave'), ('finalizada', 'Competencia finalizada')], default='inscripcion', help_text='Avance general de esta competencia (independiente de las demás categorías).', max_length=25),
        ),
        migrations.AddField(
            model_name='categoria',
            name='grupos_publicacion',
            field=models.CharField(choices=[('sin_definir', 'Sin definir'), ('borrador', 'Borrador'), ('publicada', 'Publicada')], default='sin_definir', help_text='Visibilidad de la fase de grupos para los jugadores.', max_length=12),
        ),
        migrations.AddField(
            model_name='categoria',
            name='grupos_publicados_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='grupos_publicados_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria',
            name='llave_publicacion',
            field=models.CharField(choices=[('sin_definir', 'Sin definir'), ('borrador', 'Borrador'), ('publicada', 'Publicada')], default='sin_definir', help_text='Visibilidad de la llave eliminatoria para los jugadores.', max_length=12),
        ),
        migrations.AddField(
            model_name='categoria',
            name='llave_publicada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='llave_publicada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='usuario_2',
            field=models.ForeignKey(blank=True, help_text='Cuenta del compañero (Jugador 2), si tiene una con ese DNI. Es solo un vínculo: NO modifica las categorías declaradas en esta inscripción, que quedan como dato histórico aunque el jugador cambie después su categoría oficial.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones_como_companero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DisponibilidadInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_desde', models.TimeField()),
                ('hora_hasta', models.TimeField()),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='torneos.inscripcion')),
            ],
            options={
                'ordering': ['dia', 'hora_desde'],
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_hasta__gt', models.F('hora_desde'))), name='disponibilidad_hora_hasta_mayor_que_desde')],
            },
        ),
    ]
