# Generated by Django 5.2.15 on 2026-10-05 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0010_categoria_etapa_categoria_grupos_publicacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionIdentidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(db_index=True, help_text='DNI normalizado (solo dígitos).', max_length=20)),
                ('motivo', models.CharField(choices=[('dni_ambiguo', 'DNI coincide con varias cuentas')], default='dni_ambiguo', max_length=20)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('resuelta', 'Resuelta')], default='abierta', max_length=10)),
                ('detectada_en', models.DateTimeField(auto_now_add=True)),
                ('nota_resolucion', models.TextField(blank=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('cuentas', models.ManyToManyField(blank=True, help_text='Cuentas que comparten ese DNI.', related_name='revisiones_identidad', to=settings.AUTH_USER_MODEL)),
                ('inscripciones', models.ManyToManyField(blank=True, help_text='Inscripciones cuyo compañero no se pudo identificar por este motivo.', related_name='revisiones_identidad', to='torneos.inscripcion')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('titular_verificado', models.ForeignKey(blank=True, help_text='Cuenta que, tras verificar su identidad, es la titular de ese DNI. Vacío si ninguna de las cuentas corresponde.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'revisión de identidad',
                'verbose_name_plural': 'revisiones de identidad',
                'ordering': ['-detectada_en'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'abierta')), fields=('dni', 'motivo'), name='revision_identidad_una_abierta_por_dni'), models.CheckConstraint(condition=models.Q(models.Q(('estado', 'abierta'), ('resuelta_en__isnull', True)), models.Q(('estado', 'resuelta'), ('resuelta_en__isnull', False)), _connector='OR'), name='revision_identidad_resuelta_tiene_fecha')],
            },
        ),
    ]
