# Generated by Django 5.2.15 on 2026-10-06 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_identidad_dni_unico"),
        ('accounts', '0010_identidad_dni_unico'),
        ('torneos', '0011_revisionidentidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='persona_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_como_jugador_1', to='accounts.identidad'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='persona_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_como_jugador_2', to='accounts.identidad'),
        ),
        migrations.AlterField(
            model_name='revisionidentidad',
            name='motivo',
            field=models.CharField(choices=[('dni_ambiguo', 'DNI coincide con varias identidades'), ('nombre_no_coincide', 'DNI coincide pero el nombre no'), ('vinculo_retroactivo', 'Inscripción anterior a la cuenta que usa su DNI')], default='dni_ambiguo', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.CheckConstraint(condition=models.Q(('persona_1', models.F('persona_2')), _negated=True), name='inscripcion_personas_distintas'),
        ),
    ]
