# Generated by Django 5.2.15 on 2026-10-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0013_backfill_personas_seguras'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='apellido_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='apellido_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='permite_multiples_categorias',
            field=models.BooleanField(default=False, help_text='Si está activado, un jugador puede inscribirse en más de una categoría del torneo: solo en categorías MÁS ALTAS que la anterior y siempre con una pareja distinta.'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='nombre_1',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='nombre_2',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
    ]
