# Generated by Django 5.2.15 on 2026-10-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0014_inscripcion_apellidos_y_multicategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de pago/habilitación'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15),
        ),
    ]
