# Generated by Django 3.2.25 on 2025-10-30 20:39

from django.db import migrations, models
import scoreboard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(default=scoreboard.models.default_code, help_text='Código para compartir el marcador (URL)', max_length=20, unique=True)),
                ('team_a', models.CharField(default='Equipo A', max_length=50)),
                ('team_b', models.CharField(default='Equipo B', max_length=50)),
                ('set1_a', models.IntegerField(default=0)),
                ('set1_b', models.IntegerField(default=0)),
                ('set2_a', models.IntegerField(default=0)),
                ('set2_b', models.IntegerField(default=0)),
                ('set3_a', models.IntegerField(default=0)),
                ('set3_b', models.IntegerField(default=0)),
                ('current_set', models.IntegerField(default=1)),
            ],
        ),
    ]
