# Generated by Django 3.2.25 on 2025-10-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='sponsors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
