# Generated by Django 3.2.25 on 2025-11-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_match_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='mode',
            field=models.CharField(default='3_sets', help_text='3 sets o 2 sets + super tie-break', max_length=20),
        ),
    ]
