# Generated by Django 5.2.15 on 2026-09-19 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('scoreboard', '0003_match_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='organizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='accounts.organizador'),
        ),
    ]
