# Generated by Django 5.2.15 on 2026-09-19 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizador_rol_alter_organizador_tiene_cancha_and_more'),
        ('scoreboard', '0004_match_organizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='color_principal',
            field=models.CharField(default='#005ba5', max_length=7),
        ),
        migrations.AddField(
            model_name='match',
            name='jugador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='accounts.jugador'),
        ),
        migrations.AddField(
            model_name='match',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='marcadores/logos/'),
        ),
        migrations.AddField(
            model_name='match',
            name='nombre_creador',
            field=models.CharField(blank=True, help_text='Nombre de la Liga/Club/Cancha a mostrar en el marcador.', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='personalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='tipografia',
            field=models.CharField(choices=[('sans', 'Sin serif'), ('serif', 'Con serif')], default='sans', max_length=10),
        ),
    ]
