# Generated by Django 5.2.15 on 2026-10-05 13:40

import competencia.sets
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('torneos', '0010_categoria_etapa_categoria_grupos_publicacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Llave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generada_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llave', to='torneos.categoria')),
                ('generada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('grupo', 'Fase de grupos'), ('eliminatoria', 'Eliminatoria')], max_length=14)),
                ('ronda', models.CharField(blank=True, choices=[('octavos', 'Octavos de final'), ('cuartos', 'Cuartos de final'), ('semifinal', 'Semifinal'), ('final', 'Final')], default='', max_length=10)),
                ('numero', models.PositiveSmallIntegerField(blank=True, help_text='Posición dentro de la ronda (para dibujar la llave).', null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('fecha_informada_en', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente (sin fecha)'), ('programado', 'Programado'), ('resultado_informado', 'Resultado informado'), ('resultado_en_revision', 'Resultado en revisión'), ('finalizado', 'Finalizado')], default='pendiente', max_length=22)),
                ('tipo_finalizacion', models.CharField(blank=True, choices=[('normal', 'Normal'), ('wo', 'W.O.'), ('abandono', 'Abandono')], default='', help_text='Se completa al finalizar. El tratamiento de W.O./abandono en puntos y estadísticas está pendiente de definición.', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='torneos.categoria')),
                ('fecha_informada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('llave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='competencia.llave')),
                ('pareja_a', models.ForeignKey(blank=True, help_text='Nulo en la llave mientras todavía no se conoce quién llega.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='partidos_como_a', to='torneos.inscripcion')),
                ('pareja_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='partidos_como_b', to='torneos.inscripcion')),
            ],
            options={
                'ordering': ['categoria_id', 'tipo', 'zona_id', 'ronda', 'numero', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('propuestas_generadas', 'Propuestas de zonas generadas'), ('propuesta_seleccionada', 'Propuesta de zonas seleccionada'), ('grupos_publicados', 'Fase de grupos publicada'), ('partido_modificado', 'Partido modificado'), ('fecha_informada', 'Fecha de partido informada'), ('resultado_informado', 'Resultado informado'), ('resultado_confirmado', 'Resultado confirmado por el rival'), ('resultado_disputado', 'Resultado disputado'), ('resultado_resuelto', 'Disputa resuelta por el organizador'), ('resultado_corregido', 'Resultado oficial corregido'), ('llave_generada', 'Llave generada'), ('llave_publicada', 'Llave publicada'), ('competencia_finalizada', 'Competencia finalizada')], max_length=30)),
                ('detalle', models.JSONField(blank=True, default=dict, help_text='Datos útiles del cambio (p. ej. el resultado anterior al corregir).')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_auditoria', to='torneos.categoria')),
                ('usuario', models.ForeignKey(blank=True, help_text='Nulo si lo hizo el sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_auditoria', to='competencia.partido')),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PropuestaFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej.: "Opción A".', max_length=30)),
                ('cantidad_zonas', models.PositiveSmallIntegerField()),
                ('distribucion', models.JSONField(default=list, help_text='Parejas por zona, ej.: [4, 4, 3, 3].')),
                ('total_partidos', models.PositiveIntegerField(default=0)),
                ('compatibilidad', models.DecimalField(blank=True, decimal_places=2, help_text='0–100. Nulo si no había disponibilidad suficiente para calcularla.', max_digits=5, null=True)),
                ('generada_en', models.DateTimeField(auto_now_add=True)),
                ('seleccionada_en', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas_fase', to='torneos.categoria')),
                ('seleccionada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['categoria_id', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PropuestaZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej.: "A".', max_length=10)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='competencia.propuestafase')),
            ],
            options={
                'ordering': ['propuesta_id', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PropuestaAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_propuesta', to='torneos.inscripcion')),
                ('propuesta', models.ForeignKey(editable=False, help_text='Redundante con propuesta_zona.propuesta (se completa solo): permite garantizar con una restricción que una pareja aparece una sola vez por propuesta.', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='competencia.propuestafase')),
                ('propuesta_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='competencia.propuestazona')),
            ],
            options={
                'ordering': ['propuesta_zona_id', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.JSONField(help_text='Ej.: [{"a":6,"b":3},{"a":4,"b":6},{"a":10,"b":7,"tipo":"super_tiebreak"}]', validators=[competencia.sets.validar_sets])),
                ('estado', models.CharField(choices=[('informado', 'Informado (a confirmar por el rival)'), ('disputado', 'En revisión (disputado)'), ('oficial', 'Oficial')], default='informado', max_length=10)),
                ('origen', models.CharField(choices=[('jugador', 'Jugador'), ('organizador', 'Organizador')], max_length=12)),
                ('informado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('disputado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_disputa', models.TextField(blank=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('nota_resolucion', models.TextField(blank=True)),
                ('oficializado_en', models.DateTimeField(blank=True, null=True)),
                ('oficializado_via', models.CharField(blank=True, choices=[('confirmacion_rival', 'Confirmado por el rival'), ('carga_organizador', 'Cargado por el organizador'), ('resolucion_organizador', 'Resuelto por el organizador')], default='', max_length=24)),
                ('disputado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('informado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oficializado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='competencia.partido')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='torneos.categoria')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('propuesta_origen', models.ForeignKey(blank=True, help_text='Propuesta aprobada de la que salió esta zona (informativo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonas_creadas', to='competencia.propuestafase')),
            ],
            options={
                'ordering': ['categoria_id', 'orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='partido',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='competencia.zona'),
        ),
        migrations.CreateModel(
            name='ZonaPareja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('inscripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zona_asignada', to='torneos.inscripcion')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='competencia.zona')),
            ],
            options={
                'ordering': ['zona_id', 'orden'],
            },
        ),
        migrations.AddConstraint(
            model_name='propuestafase',
            constraint=models.UniqueConstraint(fields=('categoria', 'nombre'), name='propuesta_nombre_unico_por_categoria'),
        ),
        migrations.AddConstraint(
            model_name='propuestafase',
            constraint=models.UniqueConstraint(condition=models.Q(('seleccionada_en__isnull', False)), fields=('categoria',), name='propuesta_una_seleccionada_por_categoria'),
        ),
        migrations.AddConstraint(
            model_name='propuestazona',
            constraint=models.UniqueConstraint(fields=('propuesta', 'nombre'), name='propuesta_zona_nombre_unico'),
        ),
        migrations.AddConstraint(
            model_name='propuestaasignacion',
            constraint=models.UniqueConstraint(fields=('propuesta', 'inscripcion'), name='asignacion_pareja_unica_por_propuesta'),
        ),
        migrations.AddConstraint(
            model_name='resultado',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'oficial'), ('oficializado_en__isnull', False), models.Q(('oficializado_via', ''), _negated=True)), models.Q(models.Q(('estado', 'oficial'), _negated=True), ('oficializado_en__isnull', True), ('oficializado_via', '')), _connector='OR'), name='resultado_oficial_solo_si_oficializado'),
        ),
        migrations.AddConstraint(
            model_name='resultado',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'disputado'), _negated=True), ('disputado_en__isnull', False), _connector='OR'), name='resultado_disputado_requiere_fecha_disputa'),
        ),
        migrations.AddConstraint(
            model_name='resultado',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('origen', 'organizador'), _negated=True), ('estado', 'oficial'), _connector='OR'), name='resultado_del_organizador_es_oficial'),
        ),
        migrations.AddConstraint(
            model_name='zona',
            constraint=models.UniqueConstraint(fields=('categoria', 'nombre'), name='zona_nombre_unico_por_categoria'),
        ),
        migrations.AddConstraint(
            model_name='partido',
            constraint=models.CheckConstraint(condition=models.Q(('pareja_a', models.F('pareja_b')), _negated=True), name='partido_parejas_distintas'),
        ),
        migrations.AddConstraint(
            model_name='partido',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('llave__isnull', True), ('ronda', ''), ('tipo', 'grupo'), ('zona__isnull', False)), models.Q(('llave__isnull', False), ('tipo', 'eliminatoria'), ('zona__isnull', True), models.Q(('ronda', ''), _negated=True)), _connector='OR'), name='partido_tipo_coherente_con_zona_llave_ronda'),
        ),
        migrations.AddConstraint(
            model_name='partido',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'programado'), _negated=True), ('fecha_hora__isnull', False), _connector='OR'), name='partido_programado_requiere_fecha'),
        ),
        migrations.AddConstraint(
            model_name='partido',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'pendiente'), _negated=True), ('fecha_hora__isnull', True), _connector='OR'), name='partido_pendiente_no_tiene_fecha'),
        ),
        migrations.AddConstraint(
            model_name='partido',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'finalizado'), _negated=True), models.Q(('tipo_finalizacion', ''), _negated=True), _connector='OR'), name='partido_finalizado_requiere_tipo_finalizacion'),
        ),
    ]
