# Generated by Django 5.2.15 on 2026-10-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuestaasignacion',
            name='puntaje_pareja',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propuestaasignacion',
            name='ranking_incompleto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propuestafase',
            name='criterio_prioridad',
            field=models.CharField(choices=[('disponibilidad', 'Solo disponibilidad horaria'), ('ranking_luego_disponibilidad', 'Ranking primero y disponibilidad después')], default='disponibilidad', max_length=30),
        ),
        migrations.AddField(
            model_name='propuestafase',
            name='puntajes_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text="Foto de los puntos usados por pareja (incluye quién quedó 'sin ranking'), al generar."),
        ),
    ]
