# Generated by Django 5.2.15 on 2026-10-06 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0002_propuestaasignacion_puntaje_pareja_and_more'),
        ('rankings', '0001_initial'),
        ('torneos', '0013_backfill_personas_seguras'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propuestafase',
            name='ranking_version',
            field=models.ForeignKey(blank=True, help_text='Vacía = sin ranking.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propuestas_fase', to='rankings.versionranking'),
        ),
        migrations.AddConstraint(
            model_name='propuestaasignacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ranking_incompleto', True), _negated=True), ('puntaje_pareja__isnull', True), _connector='OR'), name='asignacion_incompleta_sin_puntaje'),
        ),
        migrations.AddConstraint(
            model_name='propuestafase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('criterio_prioridad', 'ranking_luego_disponibilidad'), _negated=True), ('ranking_version__isnull', False), _connector='OR'), name='propuesta_criterio_ranking_requiere_version'),
        ),
    ]
