# Generated by Django 5.2.15 on 2026-09-19 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_publico', models.CharField(help_text='Nombre visible para jugadores (ej: nombre de la Liga o del club).', max_length=100)),
                ('tiene_cancha', models.BooleanField(default=False, help_text='Además de organizar torneos, gestiona cancha(s) propia(s).')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizadores/logos/')),
                ('color_primario', models.CharField(blank=True, help_text='Color de marca en hex, ej: #1B5E20', max_length=7)),
                ('color_secundario', models.CharField(blank=True, max_length=7)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organizador',
                'verbose_name_plural': 'Organizadores',
            },
        ),
    ]
