# Generated by Django 5.2.15 on 2026-09-19 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='rol',
            field=models.CharField(choices=[('dueno_cancha', 'Dueño de cancha'), ('liga', 'Representante de Liga')], default='liga', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='tiene_cancha',
            field=models.BooleanField(default=False, help_text='Gestiona cancha(s) propia(s) (siempre True para Dueño de cancha).'),
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jugador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
            },
        ),
    ]
