# Generated by Django 5.2.15 on 2026-09-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizador_rol_alter_organizador_tiene_cancha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizador',
            name='nombre_publico',
        ),
        migrations.AddField(
            model_name='organizador',
            name='es_liga',
            field=models.BooleanField(default=False, help_text='También representa una Liga.'),
        ),
        migrations.AddField(
            model_name='organizador',
            name='nombre_cancha',
            field=models.CharField(blank=True, help_text='Nombre de la cancha (si tiene_cancha).', max_length=100),
        ),
        migrations.AddField(
            model_name='organizador',
            name='nombre_liga',
            field=models.CharField(blank=True, help_text='Nombre de la Liga (si es_liga).', max_length=100),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='rol',
            field=models.CharField(choices=[('dueno_cancha', 'Dueño de cancha'), ('liga', 'Representante de Liga')], default='liga', help_text='Rol elegido al registrarse.', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='tiene_cancha',
            field=models.BooleanField(default=False, help_text='Gestiona cancha(s) propia(s). Habilita el Turnero de canchas.'),
        ),
    ]
