# Generated by Django 5.2.15 on 2026-09-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_organizador_nombre_publico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='celular',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='organizador',
            name='celular',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
