# Generated by Django 5.2.15 on 2026-09-22 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_jugador_celular_organizador_celular'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Identidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('ultimo_perfil', models.CharField(blank=True, choices=[('jugador', 'Jugador'), ('organizador', 'Organizador')], help_text='Último perfil usado (solo relevante si tiene los dos habilitados).', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identidad',
                'verbose_name_plural': 'Identidades',
            },
        ),
    ]
