# Generated by Django 5.2.15 on 2026-09-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_identidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='identidad',
            name='localidad',
            field=models.CharField(blank=True, help_text='Ciudad/localidad de la persona. Se pide en el registro; queda en blanco en cuentas creadas antes de agregar este campo.', max_length=100),
        ),
    ]
