# Generated by Django 5.2.15 on 2026-09-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_identidad_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='categoria_oficial',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1ra'), (2, '2da'), (3, '3ra'), (4, '4ta'), (5, '5ta'), (6, '6ta'), (7, '7ma'), (8, '8va')], help_text='1ra es la categoría más alta. Se carga en la primera inscripción a un torneo y solo se puede mejorar (bajar el número) después, nunca empeorar.', null=True),
        ),
    ]
