# Generated by Django 5.2.15 on 2026-10-06 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_jugador_categoria_oficial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoIdentidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('cuenta_con_identidad', 'Cuenta registrada con identidad propia'), ('persona_creada', 'Identidad sin cuenta creada'), ('reclamo_creado', 'Reclamo de identidad abierto'), ('reclamo_verificado', 'Reclamo verificado por el staff'), ('reclamo_rechazado', 'Reclamo rechazado por el staff'), ('reclamo_en_conflicto', 'Reclamo marcado en conflicto'), ('identidad_propia_creada', 'Identidad propia creada tras un rechazo'), ('revision_resuelta', 'Caso de revisión de DNI resuelto')], max_length=30)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'evento de identidad',
                'verbose_name_plural': 'eventos de identidad',
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MembresiaOrganizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'membresía de organizador',
                'verbose_name_plural': 'membresías de organizador',
            },
        ),
        migrations.CreateModel(
            name='PermisoMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('rankings', 'Rankings'), ('torneos', 'Torneos'), ('canchas', 'Canchas'), ('miembros', 'Miembros y permisos')], max_length=10)),
                ('nivel', models.CharField(choices=[('usar', 'Usar'), ('administrar', 'Administrar')], max_length=12)),
            ],
            options={
                'verbose_name': 'permiso de membresía',
                'verbose_name_plural': 'permisos de membresía',
            },
        ),
        migrations.CreateModel(
            name='ReclamoIdentidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_declarado', models.CharField(max_length=20)),
                ('dni_normalizado', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=20)),
                ('nombre_declarado', models.CharField(blank=True, max_length=150)),
                ('localidad_declarada', models.CharField(blank=True, max_length=100)),
                ('indicios', models.JSONField(blank=True, default=dict, help_text='Orientación para el staff; NO es verificación.')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de verificación'), ('verificado', 'Verificado'), ('rechazado', 'Rechazado'), ('en_conflicto', 'En conflicto (otra cuenta ya fue verificada)')], default='pendiente', max_length=14)),
                ('metodo_verificacion', models.CharField(blank=True, choices=[('documento_en_sede', 'Documento presentado en sede'), ('documento_digital', 'Documento enviado digitalmente'), ('otro', 'Otro (detallar en la nota)')], max_length=20)),
                ('nota_resolucion', models.TextField(blank=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'reclamo de identidad',
                'verbose_name_plural': 'reclamos de identidad',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='identidad',
            name='dni_en_revision',
            field=models.BooleanField(default=False, help_text='DNI ambiguo (varias identidades lo comparten): no participa de la unicidad hasta resolverlo.'),
        ),
        migrations.AddField(
            model_name='identidad',
            name='dni_normalizado',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, help_text='Solo dígitos. Es el que se usa para comparar.', max_length=20),
        ),
        migrations.AddField(
            model_name='identidad',
            name='nombre',
            field=models.CharField(blank=True, help_text='Apellido y nombre declarados. Se usa solo para identidades sin cuenta; con cuenta manda el nombre del usuario.', max_length=150),
        ),
        migrations.AddField(
            model_name='identidad',
            name='origen',
            field=models.CharField(choices=[('cuenta', 'Alta de cuenta'), ('inscripcion', 'Inscripción de un compañero'), ('migracion', 'Migración de datos históricos'), ('importacion_ranking', 'Importación de ranking')], default='cuenta', max_length=20),
        ),
        migrations.AlterField(
            model_name='identidad',
            name='dni',
            field=models.CharField(help_text='Como se tipeó la primera vez (dato histórico).', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='identidad',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identidad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='identidad',
            constraint=models.CheckConstraint(condition=models.Q(('usuario__isnull', False), models.Q(('nombre', ''), _negated=True), _connector='OR'), name='identidad_sin_cuenta_requiere_nombre'),
        ),
        migrations.AddField(
            model_name='eventoidentidad',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Quién lo hizo (vacío si fue el sistema).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventoidentidad',
            name='cuenta',
            field=models.ForeignKey(blank=True, help_text='Cuenta involucrada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventoidentidad',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='accounts.identidad'),
        ),
        migrations.AddField(
            model_name='membresiaorganizador',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='accounts.organizador'),
        ),
        migrations.AddField(
            model_name='membresiaorganizador',
            name='otorgada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membresiaorganizador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_organizador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permisomembresia',
            name='membresia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='accounts.membresiaorganizador'),
        ),
        migrations.AddField(
            model_name='reclamoidentidad',
            name='candidatas',
            field=models.ManyToManyField(blank=True, related_name='reclamos_como_candidata', to='accounts.identidad'),
        ),
        migrations.AddField(
            model_name='reclamoidentidad',
            name='persona',
            field=models.ForeignKey(blank=True, help_text='Candidata única, si la hay. Vacía cuando hay varias o el DNI está en revisión.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reclamos', to='accounts.identidad'),
        ),
        migrations.AddField(
            model_name='reclamoidentidad',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reclamoidentidad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamos_identidad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventoidentidad',
            name='reclamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='accounts.reclamoidentidad'),
        ),
        migrations.AddConstraint(
            model_name='membresiaorganizador',
            constraint=models.UniqueConstraint(fields=('organizador', 'usuario'), name='membresia_unica_por_cuenta_y_entidad'),
        ),
        migrations.AddConstraint(
            model_name='permisomembresia',
            constraint=models.UniqueConstraint(fields=('membresia', 'area'), name='permiso_unico_por_area'),
        ),
        migrations.AddConstraint(
            model_name='reclamoidentidad',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'en_conflicto'])), fields=('usuario',), name='reclamo_un_abierto_por_cuenta'),
        ),
        migrations.AddConstraint(
            model_name='reclamoidentidad',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'verificado')), fields=('persona',), name='reclamo_un_verificado_por_persona'),
        ),
        migrations.AddConstraint(
            model_name='reclamoidentidad',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado__in', ['pendiente', 'en_conflicto']), ('resuelto_en__isnull', True)), models.Q(('estado', 'rechazado'), ('resuelto_en__isnull', False)), models.Q(('estado', 'verificado'), ('persona__isnull', False), ('resuelto_en__isnull', False)), _connector='OR'), name='reclamo_resolucion_coherente'),
        ),
    ]
