# Generated by Django 5.2.15 on 2026-10-06 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_identidad_dni_unico'),
        ('torneos', '0013_backfill_personas_seguras'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej.: "Ranking Necochea".', max_length=150)),
                ('tipo', models.CharField(choices=[('general_gpadel', 'Ranking general GPADEL'), ('externo', 'Ranking externo')], default='externo', max_length=15)),
                ('ambito', models.CharField(blank=True, help_text='Alcance geográfico opcional (texto libre).', max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('visibilidad', models.CharField(choices=[('publico', 'Público: otros organizadores pueden consultarlo y usarlo en sus torneos'), ('privado', 'Privado: solo la entidad y sus usuarios autorizados')], default='privado', max_length=10)),
                ('por_categoria', models.BooleanField(default=False, help_text='Sí: listas independientes por categoría. No: una sola lista general. No se puede cambiar una vez publicada la primera versión.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(blank=True, help_text='Entidad responsable. Vacía solo en el ranking general de GPADEL.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rankings', to='accounts.organizador')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReglaPuntaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('vigente', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'reglas de puntaje',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TemporadaRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej.: "2026".', max_length=60)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='rankings.ranking')),
            ],
            options={
                'ordering': ['ranking_id', '-fecha_desde', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TorneoPuntuable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuable', models.BooleanField(default=False)),
                ('decidido_en', models.DateTimeField(blank=True, null=True)),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('regla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rankings.reglapuntaje')),
                ('temporada', models.ForeignKey(help_text='Temporada del ranking general a la que aportaría.', on_delete=django.db.models.deletion.PROTECT, related_name='torneos_puntuables', to='rankings.temporadaranking')),
                ('torneo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puntuabilidad', to='torneos.torneo')),
            ],
            options={
                'verbose_name': 'torneo puntuable',
                'verbose_name_plural': 'torneos puntuables',
            },
        ),
        migrations.CreateModel(
            name='VersionRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada')], default='borrador', max_length=10)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('publicada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('publicada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='rankings.temporadaranking')),
            ],
            options={
                'ordering': ['temporada_id', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='PuntajeRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, help_text='Etiqueta de la lista, propia de este ranking. Vacía si el ranking no es por categoría. Independiente de la categoría oficial de GPADEL.', max_length=60)),
                ('puntos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posicion', models.PositiveIntegerField(blank=True, null=True)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('importado', 'Importado'), ('calculado', 'Calculado')], default='manual', max_length=10)),
                ('dni_original', models.CharField(blank=True, help_text='DNI tal como vino (importaciones).', max_length=20)),
                ('dni_normalizado', models.CharField(blank=True, default='', editable=False, max_length=20)),
                ('nombre_original', models.CharField(blank=True, max_length=150)),
                ('estado_vinculo', models.CharField(choices=[('vinculado', 'Vinculado a una identidad'), ('pendiente', 'Pendiente de vincular'), ('en_revision', 'En revisión (ambiguo o dudoso)')], default='vinculado', max_length=12)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puntajes_ranking', to='accounts.identidad')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to='rankings.versionranking')),
            ],
            options={
                'ordering': ['version_id', 'categoria', 'posicion', '-puntos'],
            },
        ),
        migrations.AddConstraint(
            model_name='ranking',
            constraint=models.UniqueConstraint(condition=models.Q(('entidad__isnull', False)), fields=('entidad', 'nombre'), name='ranking_nombre_unico_por_entidad'),
        ),
        migrations.AddConstraint(
            model_name='ranking',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'general_gpadel')), fields=('tipo',), name='un_solo_ranking_general'),
        ),
        migrations.AddConstraint(
            model_name='ranking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entidad__isnull', True), ('tipo', 'general_gpadel'), ('visibilidad', 'publico')), models.Q(('entidad__isnull', False), ('tipo', 'externo')), _connector='OR'), name='ranking_tipo_coherente_con_entidad_y_visibilidad'),
        ),
        migrations.AddConstraint(
            model_name='temporadaranking',
            constraint=models.UniqueConstraint(fields=('ranking', 'nombre'), name='temporada_nombre_unico_por_ranking'),
        ),
        migrations.AddConstraint(
            model_name='temporadaranking',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_desde__isnull', True), ('fecha_hasta__isnull', True), ('fecha_hasta__gte', models.F('fecha_desde')), _connector='OR'), name='temporada_fechas_coherentes'),
        ),
        migrations.AddConstraint(
            model_name='torneopuntuable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('puntuable', True), _negated=True), ('regla__isnull', False), _connector='OR'), name='torneo_puntuable_requiere_regla'),
        ),
        migrations.AddConstraint(
            model_name='versionranking',
            constraint=models.UniqueConstraint(fields=('temporada', 'numero'), name='version_numero_unico_por_temporada'),
        ),
        migrations.AddConstraint(
            model_name='versionranking',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'borrador')), fields=('temporada',), name='un_borrador_por_temporada'),
        ),
        migrations.AddConstraint(
            model_name='versionranking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'borrador'), ('publicada_en__isnull', True)), models.Q(('estado', 'publicada'), ('publicada_en__isnull', False)), _connector='OR'), name='version_publicada_tiene_fecha'),
        ),
        migrations.AddConstraint(
            model_name='puntajeranking',
            constraint=models.UniqueConstraint(condition=models.Q(('persona__isnull', False)), fields=('version', 'persona', 'categoria'), name='puntaje_unico_por_persona_y_lista'),
        ),
        migrations.AddConstraint(
            model_name='puntajeranking',
            constraint=models.UniqueConstraint(condition=models.Q(('dni_normalizado', ''), _negated=True), fields=('version', 'dni_normalizado', 'categoria'), name='puntaje_unico_por_dni_y_lista'),
        ),
        migrations.AddConstraint(
            model_name='puntajeranking',
            constraint=models.CheckConstraint(condition=models.Q(('puntos__gte', 0)), name='puntaje_puntos_no_negativos'),
        ),
        migrations.AddConstraint(
            model_name='puntajeranking',
            constraint=models.CheckConstraint(condition=models.Q(('posicion__isnull', True), ('posicion__gte', 1), _connector='OR'), name='puntaje_posicion_valida'),
        ),
        migrations.AddConstraint(
            model_name='puntajeranking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado_vinculo', 'vinculado'), _negated=True), ('persona__isnull', False), _connector='OR'), name='puntaje_vinculado_requiere_persona'),
        ),
    ]
