# Generated by Django 5.2.15 on 2026-09-23 14:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_identidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('techada', models.BooleanField(default=False)),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hora_apertura', models.TimeField(default=datetime.time(8, 0))),
                ('hora_cierre', models.TimeField(default=datetime.time(23, 0))),
                ('duracion_turno_minutos', models.PositiveIntegerField(default=90)),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canchas', to='accounts.organizador')),
            ],
            options={
                'ordering': ['ciudad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.cancha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
    ]
